// <auto-generated />
namespace EnglishExams.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_TestResult_QuestionResult_Relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_TestResult_QuestionResult_Relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201811111540450_Added_TestResult_QuestionResult_Relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
